/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dissertation_backend_JNIBridge */

#ifndef _Included_dissertation_backend_JNIBridge
#define _Included_dissertation_backend_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dissertation_backend_JNIBridge
 * Method:    getNativeGreetingMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dissertation_backend_JNIBridge_getNativeGreetingMessage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
