/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dissertation_backend_JNIBridge */

#ifndef _Included_dissertation_backend_JNIBridge
#define _Included_dissertation_backend_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dissertation_backend_JNIBridge
 * Method:    getDistanceWithKey
 * Signature: ([[C[[C[C)[C
 */
JNIEXPORT jcharArray JNICALL Java_dissertation_backend_JNIBridge_getDistanceWithKey
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jcharArray);

/*
 * Class:     dissertation_backend_JNIBridge
 * Method:    getDistance
 * Signature: ([[C[[C)[C
 */
JNIEXPORT jcharArray JNICALL Java_dissertation_backend_JNIBridge_getDistance
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     dissertation_backend_JNIBridge
 * Method:    getMultiKeyDistance
 * Signature: ([[C[[C[C[C[C[C)Ldissertation/backend/CiphertextWrapper;
 */
JNIEXPORT jobject JNICALL Java_dissertation_backend_JNIBridge_getMultiKeyDistance
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jcharArray, jcharArray, jcharArray, jcharArray);

/*
 * Class:     dissertation_backend_JNIBridge
 * Method:    getAltitudeDifference
 * Signature: ([C[C)[C
 */
JNIEXPORT jcharArray JNICALL Java_dissertation_backend_JNIBridge_getAltitudeDifference
  (JNIEnv *, jobject, jcharArray, jcharArray);

/*
 * Class:     dissertation_backend_JNIBridge
 * Method:    getMultiKeyAltitudeDifference
 * Signature: ([C[C[C[C[C[C)Ldissertation/backend/CiphertextWrapper;
 */
JNIEXPORT jobject JNICALL Java_dissertation_backend_JNIBridge_getMultiKeyAltitudeDifference
  (JNIEnv *, jobject, jcharArray, jcharArray, jcharArray, jcharArray, jcharArray, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
